language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abdullahhameed/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abdullahhameed/docker-react npm run test

deploy:
  provider: elsaticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-586331799312"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY